name: flutter_fitness
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.3.3"
  flutter: 3.3.3

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  formz: ^0.4.1
  hexcolor: ^3.0.1
  home:
    path: packages/home
  intl: ^0.17.0
  local_storage_workouts_api:
    path: packages/local_storage_workouts_api
  user_repository:
    path: packages/user_repository
  workouts_api:
    path: packages/workouts_api
  workouts_repository:
    path: packages/workouts_repository

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
