name: workouts_repository
description: Flutter Fitness Workouts Repo
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  uuid: ^3.0.6
  workouts_api:
    path: ../workouts_api


dev_dependencies:
  very_good_analysis: ^3.0.1
