name: user_profile
description: User profile module
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.3.3"
  flutter: 3.3.3

dependencies:
  authentication_repository:
    path: ../authentication_repository
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  user_repository:
    path: ../user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
