name: authentication_repository
description: Flutter Fitness Authentication Repo
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.3.3"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
