name: login
description: Login module
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.3.3"
  flutter: 3.3.3

dependencies:
  authentication_repository:
    path: '../authentication_repository'
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  formz: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
