name: workouts_api
description: Workouts API Interface
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.3.3"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.7.0
  meta: ^1.8.0
  uuid: ^3.0.6

dev_dependencies: 
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  test: ^1.21.6
  very_good_analysis: ^3.1.0
