name: home
description: Home page module
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.3.3"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  user_profile:
    path: '../user_profile'
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
